<?php
$config['curl_path']=__DIR__.'/../function/curl.php';
$config['valid_time']=3600;
$config['available_oj']=array(
	'cf'=>'cf.php',
	'hdu'=>'hdu.php',
	'poj'=>'poj.php',
	'tioj'=>'tioj.php',
	'toj'=>'toj.php',
	'zj'=>'zj.php'
);
$config['login']['zj']=array('acct'=>'acct','pass'=>'pass');
?>